image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  DB_NAME: marketplace
  DB_USER: pipeline

  HEDERA_NETWORK: testnet
  HEDERA_NEW_ACCOUNT_INITIAL_HBAR: "100"

stages:
  - lint
  - test

# Frontend
frontend-lint:
  stage: lint
  image: node:20-slim
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - frontend/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  script:
    - cd frontend
    - npm ci
    - npm run lint

frontend-test:
  stage: test
  image: node:20-slim
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - frontend/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  script:
    - cd frontend
    - npm ci
    - npm run test -- --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/' # this does coverage badges
  artifacts:
    when: always
    reports:
      junit: frontend/coverage/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: frontend/coverage/cobertura-coverage.xml


# Backend
backend-lint:
  stage: lint
  image: eclipse-temurin:21-jdk
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - backend/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew checkstyleMain

backend-test:
  stage: test
  image: eclipse-temurin:21-jdk
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - backend/**/*
        - database/database_init/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  services:
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_DATABASE: $DB_NAME
    MYSQL_USER: $DB_USER
    MYSQL_PASSWORD: $DB_PASSWORD
    MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
  script:
    - apt-get update && apt-get install -y mysql-client
    - cat database/database_init/*.sql | mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE
    - cd backend
    - chmod +x gradlew
    - ./gradlew test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, " % covered" }' build/reports/jacoco/test/jacocoTestReport.csv
  coverage: '/(\d+\.\d+) \% covered/' # Code coverage for badges
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: backend/build/reports/jacoco/test/jacocoTestReport.xml

# Crypto
crypto-lint:
  stage: lint
  image: eclipse-temurin:21-jdk
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - rpc_currency/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  script:
    - cd rpc_currency
    - chmod +x gradlew
    - ./gradlew checkstyleMain

crypto-test:
  stage: test
  image: eclipse-temurin:21-jdk
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - rpc_currency/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  variables:
    OPERATOR_ID: $HEDERA_OPERATOR_ID
    OPERATOR_KEY: $HEDERA_OPERATOR_KEY
    RPC_CURRENCY_ID: $RPC_CURRENCY_ID
  script:
    - cd rpc_currency
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, " % covered" }' build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv
  coverage: '/(\d+\.\d+) \% covered/'
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml

# Database
database-lint:
  stage: lint
  image: python:3.11-slim
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - database/**/*
        - .gitlab-ci.yml
        - .env
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: on_success
  script:
    - pip install sqlfluff==4.0.4
    - sqlfluff lint database/database_init --dialect mysql
