services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:5173" # Host port 3000 [can change if needed], container port 5173 [DO NOT CHANGE, vite listens on port 5173]
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:8080" # Host port 3001 [can change if needed], container port 8080 [DO NOT CHANGE, spring boot listens on port 8080]
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  database:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3002:3306" # Host port 3002 [can change if needed], container port 3306 [DO NOT CHANGE, mysql listens on port 3306]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
