services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173" # Host port 3000 [can change if needed], container port 5173 [DO NOT CHANGE, vite listens on port 5173]
    environment:
      - VITE_API_URL=http://backend:8080

  backend:
    build: ./backend
    ports:
      - "3001:8080" # Host port 3001 [can change is needed], container port 8080 [DO NOT CHANGE, spring boot listens on port 8080]
