services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:5173" # Host port 3000 [can change if needed], container port 5173 [DO NOT CHANGE, vite listens on port 5173]
    environment:
      - VITE_API_URL=http://backend:8080

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:8080" # Host port 3001 [can change if needed], container port 8080 [DO NOT CHANGE, spring boot listens on port 8080]
    depends_on:
      - database

  database:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3002:3306" # Host port 3002 [can change if needed], container port 3306 [DO NOT CHANGE, mysql listens on port 3306]
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
